# Generated by Django 2.0.4 on 2018-11-03 21:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaAdultos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('servicio_solicitado', models.CharField(choices=[('Neuropsicologia', 'Neuropsicologia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Salud ocupacional', 'Salud ocupacional'), ('Psicologia', 'Psicologia'), ('Fisioterapia', 'Fisioterapia'), ('Valoracion integral', 'Valoracion integral'), ('Neurologia', 'Neurologia'), ('Terapia ocupacional', 'Terapia ocupacional')], max_length=100)),
                ('eps_afiliada', models.CharField(choices=[('Medimas', 'Medimas'), ('Emssanar', 'Emssanar'), ('Nueva EPS', 'Nueva EPS'), ('Sanitas', 'Sanitas'), ('Comfamiliar de nariño', 'Comfamiliar de nariño'), ('Policia Nacional', 'Policia Nacional'), ('Ejercito Nacional', 'Ejercito Nacional'), ('Particular', 'Particular')], max_length=100)),
                ('ingreso', models.DateField()),
                ('nivel_educativo', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Tecnico/Tecnologo', 'Tecnico/Tecnologo'), ('Profesional', 'Profesional'), ('Profesional Especialista', 'Profesional Especialista'), ('Profesional Magister', 'Profesional Magister'), ('Estudios Avanzados', 'Estudios Avanzados')], max_length=100)),
                ('remitido_por', models.CharField(max_length=50)),
                ('motivo_consulta', models.TextField(max_length=500)),
                ('historias_medicas', multiselectfield.db.fields.MultiSelectField(choices=[('Lesiones en la cabeza', 'Lesiones en la cabeza'), ('Dificultades auditivas', 'Dificultades auditivas'), ('Dificultades visuales', 'Dificultades visuales'), ('Hospitalizaciones', 'Hospitalizaciones'), ('Convulsiones', 'Convulsiones'), ('Problemas emocionales', 'Problemas emocionales'), ('Problemas de conducta', 'Problemas de conducta'), ('Trastornos de alimentacion', 'Trastornos de alimentacion'), ('Accidentes', 'Accidentes'), ('Alteraciones dermatologicas', 'Alteraciones dermatologicas'), ('Alergias', 'Alergias'), ('Ha recibido tratamiento psicologico psiquiatrico', 'Ha recibido tratamiento psicologico psiquiatrico'), ('Cefaleas', 'Cefaleas'), ('Afecciones gastrointestinales', 'Afecciones gastrointestinales'), ('Afecciones osteomusculares', 'Afecciones osteomusculares'), ('Afecciones respiratorias', 'Afecciones respiratorias'), ('Trastornos neuromotores', 'Trastornos neuromotores'), ('Afeccion cardiaca', 'Afeccion cardiaca'), ('Problemas de tiroides', 'Problemas de tiroides'), ('Diabetes', 'Diabetes')], max_length=429)),
                ('diagnostico_actual', models.TextField(max_length=500)),
                ('estado_actual_enfermedad', models.TextField(max_length=500)),
                ('tratamiendo_actual', models.TextField(max_length=500)),
                ('antecedentes', models.TextField(max_length=500)),
                ('habitos_estilo_vida', multiselectfield.db.fields.MultiSelectField(choices=[('Deportes o actividad fisica', 'Deportes o actividad fisica'), ('Consumo de cigarrillo, alcohol, otras sustancias', 'Consumo de cigarrillo, alcohol, otras sustancias'), ('Factores estresantes', 'Factores estresantes'), ('Actividades recreativas', 'Actividades recreativas')], max_length=121)),
                ('area_labor', multiselectfield.db.fields.MultiSelectField(choices=[('Actualmente tiene vinculación laboral', 'Actualmente tiene vinculación laboral'), ('Satisfacción laboral', 'Satisfacción laboral'), ('Dificultades en el desempeño laboral u ocupacional', 'Dificultades en el desempeño laboral u ocupacional'), ('Presencia de estrés laboral', 'Presencia de estrés laboral')], max_length=137)),
                ('sociofamiliar', multiselectfield.db.fields.MultiSelectField(choices=[('Conflictos de pareja', 'Conflictos de pareja'), ('Conflictos entre padres e hijos', 'Conflictos entre padres e hijos'), ('Conflictos entre hermanos', 'Conflictos entre hermanos'), ('Red de apoyo ', 'Red de apoyo '), ('Pérdidas o duelos', 'Pérdidas o duelos'), ('Consumo de alcohol o spa', 'Consumo de alcohol o spa'), ('Situaciones estresantes', 'Situaciones estresantes'), ('Cuidador', 'Cuidador')], max_length=168)),
            ],
            options={
                'verbose_name': 'Apertura Adultos',
            },
        ),
    ]
