# Generated by Django 2.0.4 on 2018-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerapiaOcupacional', '0002_auto_20181105_2006'),
        ('aperturaAdultos', '0003_auto_20181103_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaadultos',
            name='terapiaOcupacion',
            field=models.ManyToManyField(to='TerapiaOcupacional.TerapiaOcupacional'),
        ),
    ]
