# Generated by Django 2.0.4 on 2018-12-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0005_auto_20181204_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionservicios',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aperturaAdultos.AperturaAdultos'),
            preserve_default=False,
        ),
    ]
