# Generated by Django 2.0.4 on 2018-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0006_extensionservicios_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionservicios',
            name='psicologia',
            field=models.ManyToManyField(blank=True, to='Psicologia.Psicologia'),
        ),
        migrations.AlterField(
            model_name='extensionservicios',
            name='terapiaOcupacion',
            field=models.ManyToManyField(blank=True, to='TerapiaOcupacional.TerapiaOcupacional'),
        ),
    ]
