# Generated by Django 2.0.4 on 2018-12-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0003_delete_menoresdeedad'),
        ('TerapiaOcupacional', '0002_auto_20181105_2006'),
        ('aperturaAdultos', '0007_auto_20181204_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionservicios',
            name='psicologia',
        ),
        migrations.RemoveField(
            model_name='extensionservicios',
            name='terapiaOcupacion',
        ),
        migrations.AddField(
            model_name='aperturaadultos',
            name='psicologia',
            field=models.ManyToManyField(blank=True, to='Psicologia.Psicologia'),
        ),
        migrations.AddField(
            model_name='aperturaadultos',
            name='terapiaOcupacion',
            field=models.ManyToManyField(blank=True, to='TerapiaOcupacional.TerapiaOcupacional'),
        ),
    ]
