# Generated by Django 2.0.4 on 2018-12-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TerapiaOcupacional', '0002_auto_20181105_2006'),
        ('Psicologia', '0003_delete_menoresdeedad'),
        ('aperturaAdultos', '0008_auto_20181204_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaadultos',
            name='psicologia',
        ),
        migrations.AddField(
            model_name='aperturaadultos',
            name='psicologia',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Psicologia.Psicologia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='aperturaadultos',
            name='terapiaOcupacion',
        ),
        migrations.AddField(
            model_name='aperturaadultos',
            name='terapiaOcupacion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='TerapiaOcupacional.TerapiaOcupacional'),
            preserve_default=False,
        ),
    ]
