# Generated by Django 2.0.4 on 2018-12-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0009_auto_20181204_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aperturaadultos',
            options={},
        ),
    ]
