# Generated by Django 2.0.4 on 2018-12-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0010_auto_20181204_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaadultos',
            name='psicologia',
        ),
        migrations.RemoveField(
            model_name='aperturaadultos',
            name='terapiaOcupacion',
        ),
    ]
