# Generated by Django 2.0.4 on 2018-12-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0011_auto_20181204_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionservicios',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='ExtensionServicios',
        ),
    ]
