# Generated by Django 2.0.4 on 2018-11-03 21:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neuropsicologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas_neuropsicologicas', multiselectfield.db.fields.MultiSelectField(choices=[('Escala Weschler', 'Escala Weschler'), ('ENI', 'ENI'), ('Luria inicial', 'Luria inicial'), ('Banfe', 'Banfe'), ('Winsconsin', 'Winsconsin')], max_length=50)),
                ('resultados_de_la_evaluacion_neuropsicologica', models.TextField(max_length=200)),
                ('diagnostico', models.TextField(max_length=200)),
                ('plan_intervencion', multiselectfield.db.fields.MultiSelectField(choices=[('Memoria', 'Memoria'), ('Atencion', 'Atencion'), ('Lenguaje', 'Lenguaje'), ('Funciones ejectuvias', 'Funciones ejectuvias'), ('Cordinacion perceptual', 'Cordinacion perceptual')], max_length=69)),
                ('detalles_de_la_intervencion', models.TextField(max_length=500)),
                ('evolucion', models.TextField(max_length=200)),
                ('concepto', models.TextField(max_length=500)),
                ('continuidad_del_tratamiento', models.BooleanField(default=False)),
                ('valoracion_de_avance', multiselectfield.db.fields.MultiSelectField(choices=[('Memoria', 'Memoria'), ('Atencion', 'Atencion'), ('Lenguaje', 'Lenguaje'), ('Funciones ejectuvias', 'Funciones ejectuvias'), ('Cordinacion perceptual', 'Cordinacion perceptual')], max_length=69)),
                ('detalles_del_avance', models.TextField(max_length=500)),
            ],
        ),
    ]
