# Generated by Django 2.0.4 on 2018-11-06 01:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TerapiaOcupacional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapiaocupacional',
            name='comps',
        ),
        migrations.RemoveField(
            model_name='terapiaocupacional',
            name='observaciones_clinicas',
        ),
        migrations.RemoveField(
            model_name='terapiaocupacional',
            name='sipt',
        ),
        migrations.RemoveField(
            model_name='terapiaocupacional',
            name='tepsi',
        ),
        migrations.AddField(
            model_name='terapiaocupacional',
            name='pruebas_aplicadas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('COMPS', 'COMPS'), ('TEPSI', 'TEPSI'), ('OBSERVACIONES CLINCIAS I.S', 'OBSERVACIONES CLINCIAS I.S'), ('SIPT', 'SIPT')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
