# Generated by Django 2.0.4 on 2018-12-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaAdultos', '0011_auto_20181204_1830'),
        ('TerapiaOcupacional', '0002_auto_20181105_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapiaocupacional',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aperturaAdultos.AperturaAdultos'),
            preserve_default=False,
        ),
    ]
