# Generated by Django 2.0.4 on 2018-12-27 22:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TerapiaOcupacional', '0003_terapiaocupacional_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='alimentacion',
            field=models.CharField(choices=[('Sin Apoyo', 'Sin apoyo'), ('Con Apoyo', 'Con apoyo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='auditivo',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='funcion_muscular',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='funcion_postural',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='gustativo',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='higiene',
            field=models.CharField(choices=[('Sin Apoyo', 'Sin apoyo'), ('Con Apoyo', 'Con apoyo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='olfativo',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='propioceptivo',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='pruebas_aplicadas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('COMPS', 'COMPS'), ('TEPSI', 'TEPSI'), ('OBSERVACIONES CLINCIAS I.S', 'OBSERVACIONES CLINCIAS I.S'), ('SIPT', 'SIPT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='tactil',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='trofismo',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='vestibular',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='vestido',
            field=models.CharField(choices=[('Sin Apoyo', 'Sin apoyo'), ('Con Apoyo', 'Con apoyo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='terapiaocupacional',
            name='visual',
            field=models.CharField(choices=[('Presentes', 'Presentes'), ('Ausentes', 'Ausentes')], max_length=100),
        ),
    ]
