# Generated by Django 2.0.4 on 2018-12-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0008_auto_20181227_1845'),
        ('TerapiaOcupacional', '0004_auto_20181227_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terapiaocupacional',
            old_name='paciente',
            new_name='pacienteAdulto',
        ),
        migrations.AddField(
            model_name='terapiaocupacional',
            name='pacienteNiño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aperturaNinos.HistoriaNiño'),
            preserve_default=False,
        ),
    ]
