# Generated by Django 2.0.5 on 2018-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologia',
            name='caracteristicas_laborales',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
