# Generated by Django 2.0.5 on 2018-11-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0002_psicologia_caracteristicas_laborales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenoresDeEdad',
        ),
    ]
