# Generated by Django 2.0.4 on 2018-12-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0003_delete_menoresdeedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psicologia',
            options={},
        ),
    ]
