# Generated by Django 2.0.4 on 2018-12-29 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0008_auto_20181227_1845'),
        ('aperturaAdultos', '0012_auto_20181227_1748'),
        ('Psicologia', '0004_auto_20181213_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologia',
            name='pacienteAdulto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aperturaAdultos.AperturaAdultos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologia',
            name='pacienteNiño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aperturaNinos.HistoriaNiño'),
            preserve_default=False,
        ),
    ]
