# Generated by Django 2.0.4 on 2018-12-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0005_auto_20181228_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='psicologia',
            name='fecha_ingreso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
