# Generated by Django 2.0.4 on 2018-12-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psicologia', '0006_auto_20181230_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologia',
            name='pacienteNiño',
        ),
    ]
