# Generated by Django 2.0.4 on 2018-12-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PsicologiaMenores', '0002_auto_20181230_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologiamenores',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='psicologiamenores',
            name='motivo_consulta',
        ),
    ]
