# Generated by Django 2.0.4 on 2018-11-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_camino_sin_apoyo',
            new_name='camino_sin_apoyo',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_dijo_frases_simples',
            new_name='dijo_frases_simples',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_dijo_las_primeras_palabras',
            new_name='dijo_las_primeras_palabras',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_gateo',
            new_name='gateo',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_inicio_lecto_escritura',
            new_name='inicio_lecto_escritura',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_se_expreso_sin_errores_fonologicos',
            new_name='se_expreso_sin_errores_fonologicos',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_se_sento_solo',
            new_name='se_sento_solo',
        ),
        migrations.RenameField(
            model_name='historianiño',
            old_name='edad_en_la_que_sostuvo_la_cabeza',
            new_name='sostuvo_la_cabeza',
        ),
        migrations.AddField(
            model_name='historianiño',
            name='correo',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='identificacion',
            field=models.CharField(choices=[('Registro Civil ', 'Registro Civil'), ('Tarjeta Identidad', 'Tarjeta Identidad')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='lugar_nacimiento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='motivo_consulta',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='primer_apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='primer_nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='remitido_por',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historianiño',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historianiño',
            name='servicio_solicitado',
            field=models.CharField(choices=[('Neuropsicologia', 'Neuropsicologia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Salud ocupacional', 'Salud ocupacional'), ('Psicologia', 'Psicologia'), ('Fisioterapia', 'Fisioterapia'), ('Valoracion integral', 'Valoracion integral'), ('Neurologia', 'Neurologia'), ('Terapia ocupacional', 'Terapia ocupacional')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historianiño',
            name='telefono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historianiño',
            name='fecha_ingreso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historianiño',
            name='tipo_identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
