# Generated by Django 2.0.4 on 2018-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0003_auto_20181103_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historianiño',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Registro Civil ', 'Registro Civil'), ('Tarjeta Identidad', 'Tarjeta Identidad')], max_length=50),
        ),
    ]
