# Generated by Django 2.0.4 on 2018-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0004_auto_20181104_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='historianiño',
            name='frases_gramaticales',
            field=models.CharField(default=1, help_text='Años', max_length=10),
            preserve_default=False,
        ),
    ]
