# Generated by Django 2.0.4 on 2018-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperturaNinos', '0005_historianiño_frases_gramaticales'),
    ]

    operations = [
        migrations.AddField(
            model_name='historianiño',
            name='medicamentos',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
