# Generated by Django 2.0.4 on 2018-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('remitido_por', models.CharField(max_length=50)),
                ('motivo_consulta', models.TextField(max_length=500)),
                ('servicio_solicitado', models.CharField(choices=[('Neuropsicologia', 'Neuropsicologia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Salud ocupacional', 'Salud ocupacional'), ('Psicologia', 'Psicologia'), ('Fisioterapia', 'Fisioterapia'), ('Valoracion integral', 'Valoracion integral'), ('Neurologia', 'Neurologia'), ('Terapia ocupacional', 'Terapia ocupacional')], max_length=100)),
            ],
            options={
                'verbose_name': 'Informacion Persona',
            },
        ),
        migrations.CreateModel(
            name='ServicioSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Neuropsicologia', 'Neuropsicologia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Salud ocupacional', 'Salud ocupacional'), ('Psicologia', 'Psicologia'), ('Fisioterapia', 'Fisioterapia'), ('Valoracion integral', 'Valoracion integral'), ('Neurologia', 'Neurologia'), ('Terapia ocupacional', 'Terapia ocupacional')], max_length=50)),
            ],
        ),
    ]
