# Generated by Django 2.0.4 on 2018-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
