# Generated by Django 2.0.4 on 2018-07-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recepcion', '0002_persona_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='genero',
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
